### PR TITLE
Fix deprecation warnings for fetchPriority and ReactDOMTestUtils.act #508

### PR DESCRIPTION
**Pull request by adarshswaminath**
**What changed? Why?**

**1.fetchPriority prop:**
- Replaced the `Image` tag of Next.js with a standard `img` tag in `src/components/layout/banner/banner.tsx`
- Reason: To address the warning: `React does not recognize the fetchPriority prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase fetchpriority instead.`

**2.ReactDOMTestUtils.act:**
- Updated the import statement to import `act` from `react` in `src/hooks/test/useDebounce.test.ts`
- Reason: To address the `warning: ReactDOMTestUtils.act is deprecated in favor of React.act. Import act from react instead of react-dom/test-utils`

**Notes to reviewers**
- The changes are aimed at resolving specific deprecation warnings during test execution.
- No other functional changes were made to the components or tests.
- The tests were run after making these changes to ensure no new issues were introduced.

**How has it been tested?**

**Steps to Reproduce:**

1.Clone the repository:

```bash
git clone https://github.com/your-username/build-onchain-apps.git
cd build-onchain-apps
```
2.Navigate to the project directory:
```bash
cd template/web/app
```
3.Install the dependencies:
```bash
npm install
```
4.Run the tests:
```bash
npm run test
```
**Expected Behavior**
No deprecation warnings should appear.

**Actual Behavior (Before Fix)**
1.
Screenshot from 2024-05-30 15-03-31
2.
Screenshot from 2024-05-30 15-03-57

**Actual Behavior (After Fix):**
- The warnings are no longer displayed during the test run.
- All tests pass successfully.
image

### CODE REVIEW

**Comment by Zizzamia** [comment]
That's awesone @adarshswaminath 
before I merge can you make sure all the App CI check pass, please

**Comment by adarshswaminath** [comment]
Hey @Zizzamia 

I updated the yarn.lock file to ensure it's in sync with package.json and to resolve the CI errors.

If this doesn't work, could you please give me a short explanation on how I can fix it?

Thanks!

**Comment by Zizzamia** [comment]
Two things:
1. don't ship your `yarn.lock`, your code changes does not require to change yarn.
2. run `yarn check` to fix the linting issues

**Comment by adarshswaminath** [comment]
Hey @Zizzamia  I Removed yarn.lock as I'm still getting acquainted with Yarn. Changes have been pushed.

**Comment by Zizzamia** [comment]
Again, please avoid to touch the `yarn` files. :)
You are commiting a change to them.

**Pull request closed without merging**
